<?xml version = "1.0"?>

<robot name="claw_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="length_1" value="2.0"/>
	<xacro:property name="length_2" value="2.0"/>
	<xacro:property name="length_3" value="2.0"/>
	<xacro:property name="width" value="0.05"/>
	
	<material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  
  <material name="green">
    <color rgba="0 0.8 0 1"/>
  </material>
  
  <material name="clear_color">
      <color rgba="0.5 0.5 0.5 0.7"/>
  </material>
  
  <link name="world"/>
  
  <joint name="world_to_bin" type="fixed">
		<origin xyz="${(length_2/2.0)} ${(length_2/2.0)} 0.0" rpy="0.0 0.0 0.0"/>
		<parent link="world"/>
		<child link="bin"/>
	</joint>
  
  <link name="bin">
  	<visual>
			<origin xyz="0.5 0.5 1.0" rpy="0.0 0.0 0.0"/>
			<geometry>
				<box size="1.0 1.0 2.0"/>
			</geometry>
			<material name="clear_color"/>
		</visual>
  </link>

  <joint name="world_to_base" type="fixed">
		<origin xyz="0.0 0.0 ${length_1/2.0}" rpy="0.0 0.0 0.0"/>
		<parent link="world"/>
		<child link="base_link"/>
	</joint>
	
	<link name="base_link">
		<visual>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			<geometry>
				<box size="${width} ${width} ${length_1}"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			<geometry>
				<box size="${width} ${width} ${length_1}"/>
			</geometry>
		</collision>
	</link>
	
	<joint name="base_to_link1" type="prismatic">
		<origin xyz="0.0 0.0 ${length_1/2.0}" rpy="0.0 0.0 0.0"/>
		<parent link="base_link"/>
		<child link="link_1"/>
		<limit effort="1000.0" lower="0.0" upper="1.0" velocity="0.5"/>
		<axis xyz="1.0 0.0 0.0"/>
	</joint>
	
	<link name="link_1">
		<visual>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 1.57 0.0"/>
			<geometry>
				<box size="${width} ${width} ${length_2}"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
			<geometry>
				<box size="${width} ${width} ${length_2}"/>
			</geometry>
		</collision>
	</link>
	
	<joint name="link1_to_link2" type="prismatic">
		<origin xyz="${length_2/2.0} 0.0 0.0" rpy="0.0 0.0 0.0"/>
		<parent link="link_1"/>
		<child link="link_2"/>
		<limit effort="1000.0" lower="0.0" upper="1.0" velocity="0.5"/>
		<axis xyz="0.0 1.0 0.0"/>
	</joint>
	
	<link name="link_2">
		<visual>
			<origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
			<geometry>
				<box size="${width} ${width} ${length_2}"/>
			</geometry>
			<material name="blue"/>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
			<geometry>
				<box size="${width} ${width} ${length_2}"/>
			</geometry>
		</collision>
	</link>
	
	<joint name="link2_to_link3" type="prismatic">
		<origin xyz="0.0 ${length_2/2.0} -${length_3}" rpy="0.0 0.0 0.0"/>
		<parent link="link_2"/>
		<child link="link_3"/>
		<limit effort="1000.0" lower="0.0" upper="2.0" velocity="0.5"/>
		<axis xyz="0.0 0.0 1.0"/>
	</joint>
	
	<link name="link_3">
		<visual>
			<origin xyz="0.0 0.0 ${length_3/2.0}" rpy="0.0 0.0 1.57"/>
			<geometry>
				<box size="${width} ${width} ${length_3}"/>
			</geometry>
			<material name="blue"/>
		</visual>
	</link>
	
	<joint name="link3_to_claw_base" type="fixed">
		<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
		<parent link="link_3"/>
		<child link="claw_base"/>
	</joint>
	
	<link name="claw_base">
		<visual>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 1.57 0.0"/>
			<geometry>
				<box size="${width} ${width} 0.3"/>
			</geometry>
			<material name="green"/>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 1.57 0.0"/>
			<geometry>
				<box size="${width} ${width} 0.3"/>
			</geometry>
		</collision>
	</link>
	
	<joint name="claw_base_to_claw_leg1" type="fixed">
		<origin xyz="0.15 0.0 -0.075" rpy="0.0 0.0 3.14"/>
		<parent link="claw_base"/>
		<child link="claw_leg1"/>
	</joint>
	
	<link name="claw_leg1">
		<visual>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 1.57"/>
			<geometry>
				<box size="${width} ${width} 0.15"/>
			</geometry>
			<material name="green"/>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 1.57"/>
			<geometry>
				<box size="${width} ${width} 0.15"/>
			</geometry>
		</collision>
	</link>
	
	<joint name="claw_leg1_to_claw_leg2" type="prismatic">
		<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
		<parent link="claw_leg1"/>
		<child link="claw_leg2"/>
		<limit effort="1000.0" lower="0.0" upper="0.3" velocity="0.3"/>
		<axis xyz="1.0 0.0 0.0"/>
	</joint>
	
	<link name="claw_leg2">
		<visual>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 1.57"/>
			<geometry>
				<box size="${width} ${width} 0.15"/>
			</geometry>
			<material name="green"/>
		</visual>
		<collision>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 1.57"/>
			<geometry>
				<box size="${width} ${width} 0.15"/>
			</geometry>
		</collision>
	</link>
	
	
</robot>
	
